-- Dev/test seed data. Applied automatically on `pnpm db:reset` (LOCAL only).
-- Cloud baseline is maintained via direct SQL reviewed in the chat thread.
-- ON CONFLICT DO NOTHING — idempotent on repeated seed runs.

-- ── knowledge.role_substrate — first 4 reviewed ai_generated substrates ───────
-- ADR-011 base-intelligence layer. Batch 1, approved 2026-06-30.
-- onet_code: NULL — knowledge.onet_occupation is empty; FK requires a real row.
-- valid_until recalculated at seed time (now()+90d) so rows are never stale on reset.

INSERT INTO knowledge.role_substrate
  (role_key, region, onet_code, payload, basis, source, schema_version, computed_at, valid_until)
VALUES
  (
    'software engineer', 'IN', NULL,
    '{"skills":[{"name":"Data structures & algorithms","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"One backend language (Java/Python/Go/Node)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Git & version control workflows","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Databases (SQL + basic NoSQL)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"API design (REST/gRPC)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Testing & debugging","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"System design fundamentals","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Cloud basics (AWS/GCP/Azure)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"AI-assisted development (Copilot/Claude)","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,8],"common_entry_paths":["CS/IT degree","Bootcamp + projects","Self-taught + open source","Tier-2/3 college via service companies"]},"adjacent_roles":[{"role_key":"full stack developer","direction":"lateral"},{"role_key":"devops engineer","direction":"lateral"},{"role_key":"ai ml engineer","direction":"step_up"},{"role_key":"engineering manager","direction":"step_up"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'ai ml engineer', 'IN', NULL,
    '{"skills":[{"name":"Python for ML (NumPy/Pandas/PyTorch)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"ML fundamentals (supervised/unsupervised)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Deep learning & neural networks","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"LLMs & prompt engineering","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data structures & algorithms","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"MLOps & model deployment","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Statistics & probability","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Cloud ML platforms (SageMaker/Vertex)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"RAG & vector databases","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Software engineer + ML upskilling","MS/PhD in CS/ML/Stats","Data scientist transitioning to engineering","Kaggle + portfolio"]},"adjacent_roles":[{"role_key":"data scientist","direction":"lateral"},{"role_key":"software engineer","direction":"step_down"},{"role_key":"data analyst","direction":"step_down"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'product manager', 'IN', NULL,
    '{"skills":[{"name":"Product discovery & user research","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Roadmapping & prioritization","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Stakeholder management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data analysis & metrics (SQL, analytics tools)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Writing specs & user stories","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Wireframing & working with design","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Go-to-market & launch","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Technical fluency (APIs, system basics)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Strategic thinking & vision","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[2,12],"common_entry_paths":["Engineer → PM","Business analyst → PM","MBA → APM programs","Founder/early startup → PM","Consultant → PM"]},"adjacent_roles":[{"role_key":"business analyst","direction":"lateral"},{"role_key":"growth marketing manager","direction":"lateral"},{"role_key":"startup founder","direction":"step_up"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'chartered accountant', 'IN', NULL,
    '{"skills":[{"name":"Financial accounting & reporting (Ind AS)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Taxation (direct & indirect, GST)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Auditing & assurance","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Corporate & company law","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Cost & management accounting","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Financial analysis & advisory","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Excel & accounting software (Tally/SAP)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Regulatory compliance (ROC, SEBI)","proficiency":"working","criticality":"preferred","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,15],"common_entry_paths":["ICAI CA qualification (articleship + exams)","B.Com → CA","CA + CFA/MBA for advisory roles"]},"adjacent_roles":[{"role_key":"financial analyst","direction":"lateral"},{"role_key":"investment banker","direction":"step_up"},{"role_key":"business analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  )
ON CONFLICT (role_key, region) DO NOTHING;

-- ── Batch 1: 7 reviewed substrates — approved 2026-07-01 ─────────────────────
INSERT INTO knowledge.role_substrate
  (role_key, region, onet_code, payload, basis, source, schema_version, computed_at, valid_until)
VALUES
  (
    'data scientist', 'IN', NULL,
    '{"skills":[{"name":"Python/R for analysis (Pandas, scikit-learn)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Statistics & hypothesis testing","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Machine learning modeling","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"SQL & data wrangling","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data visualization & storytelling","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Experimentation & A/B testing","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Business/domain understanding","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Big data tools (Spark/cloud warehouses)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Communicating insights to stakeholders","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["MSc/Stats/Econ background","Analyst → data scientist","Bootcamp + Kaggle portfolio","Engineer + stats upskilling"]},"adjacent_roles":[{"role_key":"data analyst","direction":"step_down"},{"role_key":"ai ml engineer","direction":"lateral"},{"role_key":"business analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'ux designer', 'IN', NULL,
    '{"skills":[{"name":"User research & usability testing","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Wireframing & prototyping (Figma)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Interaction & visual design","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Information architecture","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Design systems & components","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Accessibility (WCAG basics)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Collaboration with engineering/PM","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Portfolio & case-study storytelling","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,8],"common_entry_paths":["Design degree","Bootcamp + portfolio","Graphic designer → UX","Self-taught + freelance projects"]},"adjacent_roles":[{"role_key":"product manager","direction":"lateral"},{"role_key":"content strategist","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'full stack developer', 'IN', NULL,
    '{"skills":[{"name":"Frontend framework (React/Vue/Angular)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Backend language & framework (Node/Django/Spring)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Databases (SQL + NoSQL)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"REST/GraphQL API design","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"HTML/CSS & responsive design","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Git & CI/CD basics","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Cloud deployment (AWS/Vercel/etc.)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"System design fundamentals","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"AI-assisted development","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,8],"common_entry_paths":["CS degree","Bootcamp + projects","Frontend/backend dev broadening scope","Self-taught + freelance"]},"adjacent_roles":[{"role_key":"software engineer","direction":"lateral"},{"role_key":"devops engineer","direction":"lateral"},{"role_key":"engineering manager","direction":"step_up"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'devops engineer', 'IN', NULL,
    '{"skills":[{"name":"CI/CD pipelines (Jenkins/GitHub Actions)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Containers & orchestration (Docker, Kubernetes)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Cloud platforms (AWS/GCP/Azure)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Infrastructure as Code (Terraform/Ansible)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Linux & shell scripting","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Monitoring & observability","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Networking & security basics","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Site reliability practices","proficiency":"awareness","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Software engineer → DevOps","Sysadmin → DevOps","Cloud certification + projects"]},"adjacent_roles":[{"role_key":"software engineer","direction":"lateral"},{"role_key":"full stack developer","direction":"lateral"},{"role_key":"cybersecurity analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'data analyst', 'IN', NULL,
    '{"skills":[{"name":"SQL querying","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Excel/Sheets advanced","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data visualization (Tableau/Power BI)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Descriptive statistics","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data cleaning & preparation","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Business/domain understanding","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Python basics for analysis","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Dashboarding & reporting","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,6],"common_entry_paths":["Commerce/Stats/Econ grad","Bootcamp + SQL/BI projects","Ops/support role → analyst","Fresher via analytics training"]},"adjacent_roles":[{"role_key":"data scientist","direction":"step_up"},{"role_key":"business analyst","direction":"lateral"},{"role_key":"financial analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'business analyst', 'IN', NULL,
    '{"skills":[{"name":"Requirements gathering & documentation","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Stakeholder communication","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Process mapping & analysis","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"SQL & data analysis basics","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Domain knowledge (BFSI/IT/etc.)","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Wireframing & user stories","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Agile/Scrum familiarity","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Translating business needs to specs","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Engineering/commerce grad → BA","Domain expert → BA","IT services analyst track","MBA → BA"]},"adjacent_roles":[{"role_key":"product manager","direction":"step_up"},{"role_key":"data analyst","direction":"lateral"},{"role_key":"management consultant","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'management consultant', 'IN', NULL,
    '{"skills":[{"name":"Structured problem solving","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Business analysis & frameworks","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Client communication & presentation","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Financial & market analysis","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Excel & PowerPoint mastery","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Stakeholder management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Industry/domain expertise","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Executive presence & storytelling","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,12],"common_entry_paths":["Top-tier MBA","Engineering + MBA","Analyst at consulting firm → consultant","Domain expert lateral entry"]},"adjacent_roles":[{"role_key":"business analyst","direction":"step_down"},{"role_key":"product manager","direction":"lateral"},{"role_key":"investment banker","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  )
ON CONFLICT (role_key, region) DO NOTHING;

-- ── Batch 2: 7 reviewed substrates — approved 2026-07-01 ─────────────────────
INSERT INTO knowledge.role_substrate
  (role_key, region, onet_code, payload, basis, source, schema_version, computed_at, valid_until)
VALUES
  (
    'financial analyst', 'IN', NULL,
    '{"skills":[{"name":"Financial modeling & valuation","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Excel & spreadsheet mastery","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Financial statement analysis","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Budgeting & forecasting","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Accounting fundamentals","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data analysis & SQL basics","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Presentation & reporting","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Business/industry acumen","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,8],"common_entry_paths":["Commerce/finance grad","MBA finance","CA/CFA → analyst","B.Com → analyst role"]},"adjacent_roles":[{"role_key":"investment banker","direction":"step_up"},{"role_key":"data analyst","direction":"lateral"},{"role_key":"chartered accountant","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'investment banker', 'IN', NULL,
    '{"skills":[{"name":"Financial modeling (LBO/DCF/M&A)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Valuation & comparable analysis","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Excel & PowerPoint (pitch decks)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Accounting & financial statements","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Deal structuring & due diligence","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Market & industry research","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Client & stakeholder management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Stamina & attention to detail","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,10],"common_entry_paths":["Top MBA/IIM","CA + finance","Analyst at BB/boutique → associate","Tier-1 college finance recruitment"]},"adjacent_roles":[{"role_key":"financial analyst","direction":"step_down"},{"role_key":"management consultant","direction":"lateral"},{"role_key":"vc analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'growth marketing manager', 'IN', NULL,
    '{"skills":[{"name":"Performance marketing (Google/Meta ads)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Analytics & attribution (GA4, dashboards)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"A/B testing & experimentation","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Funnel & conversion optimization","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"SEO & content marketing basics","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Email & lifecycle marketing","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"SQL/data for growth","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Growth experimentation mindset","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[2,10],"common_entry_paths":["Digital marketing → growth","Startup marketing generalist","MBA marketing → growth role","Analyst → growth"]},"adjacent_roles":[{"role_key":"digital marketing manager","direction":"lateral"},{"role_key":"product manager","direction":"lateral"},{"role_key":"data analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'digital marketing manager', 'IN', NULL,
    '{"skills":[{"name":"SEO & SEM","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Social media & content marketing","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Paid advertising (Google/Meta)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Email marketing & automation","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Analytics & reporting (GA4)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Brand & campaign management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Content creation & copywriting","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Marketing strategy & planning","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Marketing grad/MBA","Content/social executive → manager","Agency → in-house","Self-taught + certifications"]},"adjacent_roles":[{"role_key":"growth marketing manager","direction":"lateral"},{"role_key":"content strategist","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'content strategist', 'IN', NULL,
    '{"skills":[{"name":"Content strategy & planning","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Writing & editing","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"SEO & content optimization","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Audience & persona research","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Content analytics & performance","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Editorial calendar & workflow","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"AI-assisted content tools","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Brand voice & storytelling","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Content writer → strategist","Journalism/English background","Marketing generalist → content","Freelance → in-house"]},"adjacent_roles":[{"role_key":"digital marketing manager","direction":"lateral"},{"role_key":"ux designer","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'sales manager b2b saas', 'IN', NULL,
    '{"skills":[{"name":"B2B sales process & pipeline management","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"CRM tools (Salesforce/HubSpot)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Prospecting & lead qualification","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Negotiation & closing","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Product & solution knowledge","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Account management & upsell","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Sales analytics & forecasting","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Consultative selling & relationship building","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[2,12],"common_entry_paths":["Sales exec → manager","Inside sales/SDR → AE → manager","MBA → SaaS sales","Domain expert → SaaS sales"]},"adjacent_roles":[{"role_key":"customer success manager","direction":"lateral"},{"role_key":"growth marketing manager","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'customer success manager', 'IN', NULL,
    '{"skills":[{"name":"Customer relationship management","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Onboarding & adoption","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Product knowledge & troubleshooting","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Retention & churn management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Upsell & expansion","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"CRM & CS tools (Gainsight/etc.)","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Data & health-score analysis","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Empathy & stakeholder communication","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[1,10],"common_entry_paths":["Support/account mgmt → CSM","Sales → CSM","SaaS ops → CSM","Domain expert → CSM"]},"adjacent_roles":[{"role_key":"sales manager b2b saas","direction":"lateral"},{"role_key":"operations manager","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  )
ON CONFLICT (role_key, region) DO NOTHING;

-- ── Batch 3: 7 reviewed substrates — approved 2026-07-01 ─────────────────────
INSERT INTO knowledge.role_substrate
  (role_key, region, onet_code, payload, basis, source, schema_version, computed_at, valid_until)
VALUES
  (
    'human resources business partner', 'IN', NULL,
    '{"skills":[{"name":"Talent management & workforce planning","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Employee relations & engagement","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Performance management systems","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Stakeholder & leadership partnering","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"HR analytics & metrics","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Labour law & compliance (India)","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Change management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Coaching & influencing","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[3,15],"common_entry_paths":["HR generalist → HRBP","MBA HR → HRBP","Recruitment/L&D → HRBP","Domain HR specialist lateral"]},"adjacent_roles":[{"role_key":"operations manager","direction":"lateral"},{"role_key":"management consultant","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'operations manager', 'IN', NULL,
    '{"skills":[{"name":"Process design & optimization","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Team & people management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Project & program management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Data analysis & KPIs","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Vendor & stakeholder management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Budgeting & cost control","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Supply chain / logistics basics","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Cross-functional coordination","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[3,15],"common_entry_paths":["Ops executive → manager","MBA → ops role","Engineering + ops experience","Team lead → ops manager"]},"adjacent_roles":[{"role_key":"supply chain analyst","direction":"lateral"},{"role_key":"business analyst","direction":"lateral"},{"role_key":"human resources business partner","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'supply chain analyst', 'IN', NULL,
    '{"skills":[{"name":"Supply chain planning & forecasting","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Inventory & demand analysis","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Excel & data analysis","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"ERP systems (SAP/Oracle)","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Logistics & procurement basics","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"SQL / data tools","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Vendor coordination","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Analytical & problem-solving","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,10],"common_entry_paths":["Engineering/commerce grad","MBA operations/SCM","Logistics executive → analyst","Manufacturing background"]},"adjacent_roles":[{"role_key":"operations manager","direction":"step_up"},{"role_key":"data analyst","direction":"lateral"},{"role_key":"business analyst","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'cybersecurity analyst', 'IN', NULL,
    '{"skills":[{"name":"Network & systems security","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Threat detection & incident response","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"SIEM & security tools","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Vulnerability assessment","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Security frameworks (ISO 27001/NIST)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Scripting (Python/Bash)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Cloud security basics","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Security certifications (CEH/CompTIA)","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"high","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,10],"common_entry_paths":["CS/IT grad + security certs","Network/sysadmin → security","Self-taught + certifications","IT services security track"]},"adjacent_roles":[{"role_key":"devops engineer","direction":"lateral"},{"role_key":"software engineer","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'startup founder', 'IN', NULL,
    '{"skills":[{"name":"Product-market fit discovery","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Fundraising & investor relations","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Financial modeling & runway management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Hiring & team building","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Sales & early customer acquisition","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Unit economics & metrics literacy","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Indian regulatory & compliance (GST, ROC, DPIIT)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Storytelling & pitching","proficiency":"expert","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,30],"common_entry_paths":["Domain expert turned founder","Ex-startup employee","Repeat founder","Engineer/PM who built an MVP"]},"adjacent_roles":[{"role_key":"product manager","direction":"lateral"},{"role_key":"vc analyst","direction":"lateral"},{"role_key":"growth marketing manager","direction":"step_down"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'vc analyst', 'IN', NULL,
    '{"skills":[{"name":"Market & industry research","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Financial analysis & modeling","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Startup evaluation & due diligence","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Deal sourcing & networking","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Sector/thesis development","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Excel & data analysis","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Founder relationship management","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Pattern recognition & judgment","proficiency":"awareness","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"low","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[0,8],"common_entry_paths":["IB/consulting → VC","MBA → VC","Founder/operator → VC","Startup ecosystem → analyst"]},"adjacent_roles":[{"role_key":"investment banker","direction":"lateral"},{"role_key":"management consultant","direction":"lateral"},{"role_key":"startup founder","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  ),
  (
    'freelance consultant', 'IN', NULL,
    '{"skills":[{"name":"Domain expertise (specialized field)","proficiency":"expert","criticality":"required","basis":"inferred"},{"name":"Client acquisition & business development","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Project & deliverable management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Pricing & proposal writing","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Communication & stakeholder management","proficiency":"working","criticality":"required","basis":"inferred"},{"name":"Personal branding & networking","proficiency":"working","criticality":"preferred","basis":"inferred"},{"name":"Finance & invoicing (self-employment)","proficiency":"awareness","criticality":"preferred","basis":"inferred"},{"name":"Self-discipline & time management","proficiency":"working","criticality":"differentiating","basis":"inferred"}],"market":{"demand_signal":"moderate","demand_basis":"AI-inferred, India market, no live signal","typical_yoe_range":[3,30],"common_entry_paths":["Experienced professional → independent","Corporate expert → consultant","Domain specialist freelancing","Portfolio career transition"]},"adjacent_roles":[{"role_key":"management consultant","direction":"lateral"},{"role_key":"startup founder","direction":"lateral"}]}'::jsonb,
    'inferred', 'ai_generated', 'substrate/v1', now(), now() + interval '90 days'
  )
ON CONFLICT (role_key, region) DO NOTHING;
